version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: webchat
    networks:
      - app

  app:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
    environment:
      PORT: 3001
    command: npm run start:dev
    networks:
      - app

networks:
  app: